language: java
addons:
  sonarqube:
    token:
      secure: "MCe7zTh41jzDgOi5YYAyy44YAAeK2IMM7AkMPWtd2kqfgMLHHQF8YcsnCiKek7kQm3z6FVX95quIC0l7N/GZJRap7kIHGsjbzVqMgncOi6crsfox5VSGjpiFhToCBeo5kdWxH/7VjgxRPDeJsbCj8rUnmOgfTJ3hOIR+gHyykfUkaM4wmC1bHk37EOBs0m/QnvBhsVNbQquIpOZ4WeXkTB+e6p+77znpIUYzrlhOBXgoluwEshlMFE9T1m4fngC25lzqNYIKohAJeUZclet6VTdYrIjoh3ZzHiCFnQcqt3RkK9a9KRx3PemmeSuZOdiL6+fN3x18gmVJEp0SWVtlaKFe3LpPGwasWRW+hupHsuP3y1n+cOnpx7289vRHuCK2Nm2gB4K5xDLEMjeamqzj1rxccmRPPannjlaHo2uy1aaudGi2q7p0XJeJ88qfn/r9MPx7gU/togQTG8JPTwQCOumqD/qU5aBfSpIcgcUprmQVxmaJQ76I4mYiWyFdUMb1hAvN4kq0giiwsytz3kZ/dgo50BNBxaY4g9LU7Nm/nh7Qra0HsYEKFV30nPSHauKQA/6trPWPxXoYGUJc5g3NcnYP1rEO0rqa8nlemPeJUExlIPKaBTgH9xZkWNyjV27eK1IVrPA3zDX5/3S6+8aT72PoH5XqgtXIQ/KO5TzYHNc="
    branches:
      - master
      - features-*

sudo: false

jdk:
  - oraclejdk8

script: ./travis.sh
